export const tbl = {
  container:   'rounded-xl border border-border bg-card shadow-sm overflow-hidden',
  toolbar:     'flex items-center gap-3 border-b border-border px-4 py-3',
  filterRow:   'flex flex-wrap items-center gap-4 border-b border-border/60 px-4 py-3',
  searchWrap:  'relative flex-1 max-w-3xl',
  searchIcon:  'absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground/60',
  searchInput: 'w-full rounded-lg border border-border bg-background h-10 pl-10 pr-3 text-sm outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-all',
  addBtn:      'flex items-center gap-1.5 rounded-lg bg-primary px-3 h-10 text-sm font-semibold text-white hover:bg-primary/90 transition-colors shrink-0',
  theadRow:    'border-b border-border bg-muted/40',
  th:          'px-4 py-3 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground border-r border-border text-center',
  tbodyRow:    'border-b border-border/60 last:border-0 hover:bg-muted/30 transition-colors duration-150',
  td:          'px-4 py-3 text-sm text-foreground border-r border-border/60 align-middle text-center',
  tfootRow:    'border-t border-border bg-muted/40',
  tfootCell:   'px-4 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground',
  actionTd:    'px-4 py-3 text-center',
  actionGroup: 'flex items-center justify-end gap-2',
  actionBtn:   'rounded-lg h-8 w-8 p-0 flex items-center justify-center text-muted-foreground/60 transition-colors',
}
